sudo: false
language: java
jdk:
  - openjdk8
branches:
  except:
    - /.*wip.*/i
script: "mvn -T4 verify"
after_success:
- mvn test jacoco:report coveralls:report
- "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && [ ${TRAVIS_BRANCH} = 'master' ] && mvn clean deploy -DskipTests --settings ./deploy-settings.xml"
